
[window]
padding = {x = 5, y = 5}
opacity = 0.95

[font]
normal = {family = "Fira Mono", style = "Medium"}
size = 16

[cursor]
style = {shape = "Beam", blinking = "Never"}
thickness = 0.2
unfocused_hollow = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  {key = "V", mods = "Control", action = "Paste"},
]

[general]
live_config_reload = true
